### ISSUE TITLE
rustc 1.87.0 and rustc beta performance regression

### ISSUE THREAD

**Issue by arichnad** [image-rs/image-png#598]
Hello, I saw a performance regression using rustc 1.87.0 and rustc beta.

I'm using the master branch of image-png ( 56fbdc5 ).

```
for version in 1.86.0 1.87.0 beta nightly; do
  rustup install --profile minimal $version && rustup run $version cargo run --release --example=corpus-bench
done
```

I'm including a total encoding line of each version here from one computer, but I ran this on multiple hosts, and noticed similar results (similar ratios).

* 1.86.0 `233 mps  0.722 GiB/s`
* 1.87.0 `133 mps  0.412 GiB/s`
* beta `132 mps  0.410 GiB/s`
* nightly `215 mps  0.665 GiB/s`

The ratio is more visible if you disable png compression.

Let me know if there is any more information I can provide, thank you!

**Comment by 197g** [comment]
The nature of our filter implementation makes performance quite dependent on auto-vectorization. If the issue is specific to a rustc version, there is very likely an llvm regression that I would encourage reporting upstream. What's the precise environment (target tuple, host tuple, cpu, image testsuite) if someone should try to replicate this issue?

**Comment by fintelia** [comment]
[Rustc 1.87.0 upgraded to LLVM 20](https://releases.rs/docs/1.87.0/#internal-changes) so there's a good chance that's related to the slowdown.

If it is the unfiltering that's the problem, the [unfilter benchmark](https://github.com/image-rs/image-png/blob/master/benches/unfilter.rs) should show that. Would be good to construct a minimal repro and report upstream, though if the performance is better on nightly that may mean its already been fixed and just needs to be rolled out to beta/stable.

**Comment by fintelia** [comment]
On Linux with an AMD Ryzen 5600X, I'm seeing a performance drop in the paeth4 unfiltering code. Not as severe as OP, but still significant:
```
unfilter/filter=Paeth/bpp=4
                        time:   [11.177 µs 11.192 µs 11.211 µs]
                        thrpt:  [1.3610 GiB/s 1.3633 GiB/s 1.3652 GiB/s]
                 change:
                        time:   [+17.275% +17.435% +17.596%] (p = 0.00 < 0.05)
                        thrpt:  [-14.963% -14.846% -14.730%]
                        Performance has regressed.
```
